### ISSUE TITLE
消息列表显示bug

### ISSUE THREAD

**Issue by cookieiz** [mo-jinran/linux-qqnt-background-blur#1]
![a309bc67ab9e51d1ec4cd723a3a742a5](https://github.com/mo-jinran/linux-qqnt-background-blur/assets/111113097/fa0614af-00a4-490c-b1ce-c962727472b9)
![cad6bb8f4c5ed440917546d236ff9c85](https://github.com/mo-jinran/linux-qqnt-background-blur/assets/111113097/c5161d7c-cd82-4900-82eb-bf688e3c8f99)

**Comment by cookieiz** [comment]
Linux

**Comment by mo-jinran** [comment]
这属于是第三方主题的适配问题了，不过早已反馈 https://github.com/MUKAPP/BetterQQNT-MSpring-Theme/issues/12
